apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: My4xMDkuMjUzLjE4NA==
  DB_PORT: NTQzMg==
  DB_USER: aWJtX2FkbWlu
  DB_PASSWORD: MTIzX2libV8zMjE=
  DB_NAME: cG9fYmFzZQ==