# This is a basic workflow to help you get started with Actions
name: Deploy to "main"

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "develop" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world PO-Conditioning

      - name: Copy files via SSH key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRD_HOST }}
          port: ${{secrets.PORT  }}
          username: ${{  secrets.USERNAME  }}
          key: ${{ secrets.DEPLOY_KEY}}
          source: "./"
          target: "/home/ubuntu/ibm_practices/po-conditioning-backend-v1/"

      - name: Execute install.sh via SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRD_HOST }}
          port: ${{secrets.PORT  }}
          username: ${{  secrets.USERNAME  }}
          key: ${{ secrets.DEPLOY_KEY}}
          script: |
            cd /home/ubuntu/ibm_practices/po-conditioning-backend-v1/
            git clean -fd
            echo "${{ secrets.PRD_ENV }}" > "/home/ubuntu/ibm_practices/po-conditioning-backend-v1/.env"
            sh install.sh
            sh deploy.sh  